#!/usr/bin/env bash
# Create the /dev/hopejr_arm and /dev/hopejr_hand udev symlinks.
#
#   bash scripts/hopejr_udev.sh detect                      # list candidate adapters
#   bash scripts/hopejr_udev.sh generate <arm_tty> <hand_tty>   # print the rule
#   bash scripts/hopejr_udev.sh install  <arm_tty> <hand_tty>   # write it + reload (sudo)
#
# Identify which adapter is which by plugging them in ONE AT A TIME and running
# `detect` after each. The rule pins by USB serial number when the adapter has
# one; otherwise it falls back to the USB port path, which means the adapter
# must always go back into the same physical port.
if [ "${BASH_SOURCE[0]:-$0}" != "$0" ]; then
  echo "ERROR: run this, don't source it:  bash scripts/hopejr_udev.sh" >&2
  return 1
fi
set -euo pipefail

RULES=/etc/udev/rules.d/99-hopejr.rules

die() { echo "ERROR: $*" >&2; exit 1; }

# prop <tty> <udev-property>  -> value, or empty
prop() { udevadm info -q property -n "$1" 2>/dev/null | sed -n "s/^$2=//p"; }

detect() {
  local found=0 dev vid pid ser path vendor model
  for dev in /dev/ttyUSB* /dev/ttyACM*; do
    [ -e "$dev" ] || continue
    found=1
    vid=$(prop "$dev" ID_VENDOR_ID); pid=$(prop "$dev" ID_MODEL_ID)
    vendor=$(prop "$dev" ID_VENDOR); model=$(prop "$dev" ID_MODEL)
    ser=$(prop "$dev" ID_SERIAL_SHORT); path=$(prop "$dev" ID_PATH)
    echo "$dev"
    echo "    vendor:product  ${vid:-?}:${pid:-?}  (${vendor:-?} ${model:-?})"
    if [ -n "$ser" ]; then
      echo "    serial          $ser   <- rule will pin by this (robust)"
    else
      echo "    serial          (none)      <- rule will pin by port path instead:"
      echo "    path            ${path:-?}   (always use this physical port)"
    fi
  done
  [ "$found" = 1 ] || die "no /dev/ttyUSB* or /dev/ttyACM* found — is the adapter plugged in and powered?"
}

# count_vidpid <vid> <pid>  -> how many USB devices on this machine share them
count_vidpid() {
  local n=0 d
  for d in /sys/bus/usb/devices/*; do
    [ -r "$d/idVendor" ] && [ -r "$d/idProduct" ] || continue
    [ "$(cat "$d/idVendor")" = "$1" ] && [ "$(cat "$d/idProduct")" = "$2" ] && n=$((n+1))
  done
  echo "$n"
}

# rule_line <tty> <symlink-name>
#
# Three ways to pin a device, best first:
#   1. USB serial number  — unique per adapter, survives any port. Ideal.
#   2. vendor:product     — no serial number (CH340 has none: it has no serial
#                           string descriptor at all), but the chip type is
#                           unique on THIS machine. Still survives any port; only
#                           breaks if a second adapter of the same chip appears.
#   3. USB port path      — last resort. Robust against other adapters, but the
#                           device must always go back into the same socket.
rule_line() {
  local dev="$1" name="$2" vid pid ser path same
  [ -e "$dev" ] || die "$dev does not exist"
  vid=$(prop "$dev" ID_VENDOR_ID); pid=$(prop "$dev" ID_MODEL_ID)
  ser=$(prop "$dev" ID_SERIAL_SHORT); path=$(prop "$dev" ID_PATH)
  [ -n "$vid" ] && [ -n "$pid" ] || die "$dev is not a USB device (no vendor/product id)"
  if [ -n "$ser" ]; then
    printf '# %s pinned by USB serial number — any port works.\n' "$name"
    printf 'SUBSYSTEM=="tty", ATTRS{idVendor}=="%s", ATTRS{idProduct}=="%s", ATTRS{serial}=="%s", SYMLINK+="%s", MODE="0660", GROUP="dialout", ENV{ID_MM_DEVICE_IGNORE}="1"\n' \
      "$vid" "$pid" "$ser" "$name"
    return
  fi
  same=$(count_vidpid "$vid" "$pid")
  if [ "$same" = 1 ]; then
    printf '# %s has no USB serial number (e.g. CH340), but %s:%s is the only one on\n' "$name" "$vid" "$pid"
    printf '# this machine, so the chip type identifies it — any port works.\n'
    printf '# If you ever plug in a second %s:%s adapter, re-run this script.\n' "$vid" "$pid"
    printf 'SUBSYSTEM=="tty", ATTRS{idVendor}=="%s", ATTRS{idProduct}=="%s", SYMLINK+="%s", MODE="0660", GROUP="dialout", ENV{ID_MM_DEVICE_IGNORE}="1"\n' \
      "$vid" "$pid" "$name"
    return
  fi
  [ -n "$path" ] || die "$dev has no USB serial number, shares %s:%s with $same devices, and has no ID_PATH — cannot write a stable rule"
  printf '# %s has no USB serial number and %s other %s:%s adapter(s) are present —\n' "$name" "$((same-1))" "$vid" "$pid"
  printf '# pinned to a physical port; always plug it in here.\n'
  printf 'SUBSYSTEM=="tty", ENV{ID_PATH}=="%s", SYMLINK+="%s", MODE="0660", GROUP="dialout", ENV{ID_MM_DEVICE_IGNORE}="1"\n' \
    "$path" "$name"
}

generate() {
  local arm="$1" hand="$2"
  [ "$arm" != "$hand" ] || die "arm and hand are the same device ($arm) — plug in both adapters"
  echo "# HopeJR servo buses — generated by scripts/hopejr_udev.sh on $(date -I)"
  echo "# arm:  7 servos, protocol 0 (sm8512bl / sts3250)"
  echo "# hand: 16 servos, protocol 1 (scs0009)"
  echo "# ID_MM_DEVICE_IGNORE keeps ModemManager from probing the bus with AT commands."
  rule_line "$arm" hopejr_arm
  rule_line "$hand" hopejr_hand
}

case "${1:-}" in
  detect)
    detect ;;
  generate)
    [ $# -eq 3 ] || die "usage: $0 generate <arm_tty> <hand_tty>"
    generate "$2" "$3" ;;
  install)
    [ $# -eq 3 ] || die "usage: $0 install <arm_tty> <hand_tty>"
    tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT
    generate "$2" "$3" > "$tmp"
    echo "--- $RULES ---"; cat "$tmp"; echo "---"
    sudo cp "$tmp" "$RULES"
    sudo chmod 644 "$RULES"
    sudo udevadm control --reload-rules
    sudo udevadm trigger --subsystem-match=tty
    sleep 1
    ls -l /dev/hopejr_arm /dev/hopejr_hand
    id -nG "$USER" | tr ' ' '\n' | grep -qx dialout \
      || echo "NOTE: you are not in the 'dialout' group yet — run: sudo usermod -aG dialout $USER  (then log out/in)" ;;
  *)
    sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//' ; exit 1 ;;
esac
